[
	[".", "mkdir", "-p", "build-runtime"],
	["build-runtime",
		"env",
		"CC=clang",
		"CXX=clang++",
		"cmake",
		"../runtimes",
		"-DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind",
		"-DCMAKE_BUILD_TYPE=Release",
		"-DCMAKE_C_COMPILER=clang",
		"-DCMAKE_SYSTEM_NAME=zwolf",
		"-DCMAKE_C_COMPILER_TARGET=x86_64-unknown-linux-zwolf",
		"-DCMAKE_C_COMPILER_FORCED=TRUE",
		"-DCMAKE_CXX_COMPILER_FORCED=TRUE",
		"-DDEFAULT_SYSROOT=/home/silvio/stuff/sources/elf_release_linux",
		"-DCMAKE_INSTALL_PREFIX=/__zwolf_run__/llvm-libcxx",
		"-DCMAKE_INSTALL_LIBDIR=x86_64/lib",
		"-DCMAKE_INSTALL_PREFIX=/__zwolf_run__/llvm-libcxx",
		"-DCMAKE_INSTALL_INCLUDEDIR=common/include",
		"-DLIBCXX_INCLUDE_BENCHMARKS:BOOL=OFF",
		"-DLIBCXX_USE_COMPILER_RT=ON",
		"-DLIBCXX_ENABLE_DEBUG_MODE=ON",
		"-DLIBCXXABI_USE_COMPILER_RT=ON",
		"-DLIBCXXABI_USE_LLVM_UNWINDER=ON",
		"-DCOMPILER_RT_INSTALL_LIBRARY_DIR=lib",
		"-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON",
		"-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON",
		"-G", "Ninja"
	],
	["build-runtime", "ninja", "cxx", "cxxabi", "unwind"],
	["build-runtime", "env", "DESTDIR=..", "ninja", "install"],
	[".", "echo", "mkdir", "-p", "build-runtime-arm"],
	["build-runtime-arm", "echo",
		"env",
		"CC=clang",
		"CXX=clang++",
		"cmake",
		"../runtimes",
		"-DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind",
		"-DCMAKE_BUILD_TYPE=Release",
		"-DCMAKE_C_COMPILER=clang",
		"-DCMAKE_SYSTEM_NAME=zwolf",
		"-DCMAKE_C_COMPILER_TARGET=arm-unknown-linux-zwolf",
		"-DCMAKE_CXX_COMPILER_TARGET=arm-unknown-linux-zwolf",
		"-DCMAKE_ASM_COMPILER_TARGET=arm-unknown-linux-zwolf",
		"-DLLVM_DEFAULT_TARGET_TRIPLE=arm-unknown-linux-zwolf",
		"-DCMAKE_C_COMPILER_FORCED=TRUE",
		"-DCMAKE_CXX_COMPILER_FORCED=TRUE",
		"-DCMAKE_ASM_FLAGS=-march=armv7a",
		"-DCMAKE_C_FLAGS=-march=armv7a",
		"-DCMAKE_CXX_FLAGS=-march=armv7a",
		"-DDEFAULT_SYSROOT=/home/silvio/stuff/sources/elf_release_linux",
		"-DCMAKE_INSTALL_PREFIX=/__zwolf_run__/llvm-libcxx/arm",
		"-DCMAKE_INSTALL_INCLUDEDIR=/__zwolf_run__/llvm-libcxx/common/include",
		"-DLIBCXX_INCLUDE_BENCHMARKS:BOOL=OFF",
		"-DLIBCXX_USE_COMPILER_RT=ON",
		"-DLIBCXX_ENABLE_DEBUG_MODE=ON",
		"-DLIBCXXABI_USE_COMPILER_RT=ON",
		"-DLIBCXXABI_USE_LLVM_UNWINDER=ON",
		"-DCOMPILER_RT_INSTALL_LIBRARY_DIR=lib",
		"-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON",
		"-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON",
		"-G", "Ninja"
	],
	["build-runtime-arm", "echo", "ninja", "cxx", "cxxabi", "unwind"],
	["build-runtime-arm", "echo", "env", "DESTDIR=..", "ninja", "install"]
]
