name: Bootstrap
on:
  workflow_dispatch:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install ninja
      run: sudo apt-get install -y ninja-build clang s3cmd

    - name: build llvm stage1
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
      run: |
        sudo mkdir /_zwolf
        sudo chown ${USER}: /_zwolf
        ./bootstrap.sh
