name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ls
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: headers
        path: xlibc/include
